version: "3"
services:
  db:
    image: mongo
    hostname: mongodb-server
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  web:
    build: .
    command: python manage.py runserver  0.0.0.0:8000
    hostname: chatbox
    volumes:
      - ./chatbox:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx/
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./chatbox.crt:/etc/ssl/chatbox.crt
      - ./chatbox.key:/etc/ssl/chatbox.key
    ports:
      - "443:443"
    depends_on:
      - web
volumes:
  mongo_data:
